//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Semaine
    {
        public Detail_Semaine()
        {
            this.Apprentissages = new HashSet<Apprentissage>();
            this.Difficultes = new HashSet<Difficulte>();
            this.Taches = new HashSet<Tache>();
        }
    
        public int noSTAGE { get; set; }
        public int noSemaine { get; set; }
        public string synthese { get; set; }
        public string horaire { get; set; }
        public string envMateriel { get; set; }
        public string envLogiciel { get; set; }
        public string commSuperviseur { get; set; }
        public string commTuteur { get; set; }
        public bool soumisCahier { get; set; }
        public bool soumisSuperviseur { get; set; }
        public bool soumisTuteur { get; set; }
        public System.DateTime dateDebut { get; set; }
    
        public virtual ICollection<Apprentissage> Apprentissages { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<Difficulte> Difficultes { get; set; }
        public virtual ICollection<Tache> Taches { get; set; }
    }
}
