//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Difficulte
    {
        public int noDIFFIC { get; set; }
        public int noSTAGE { get; set; }
        public int noSemaine { get; set; }
        public string description { get; set; }
        public string moyen { get; set; }
        public string resultat { get; set; }
    
        public virtual Detail_Semaine Detail_Semaine { get; set; }
    }
}
