//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public Entreprise()
        {
            this.Stages = new HashSet<Stage>();
        }
    
        public int noENT { get; set; }
        public string nomENT { get; set; }
        public string adresseENT { get; set; }
        public string villeENT { get; set; }
        public string cpENT { get; set; }
        public string telENT { get; set; }
        public string faxENT { get; set; }
        public string courrielENT { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
    
        public virtual ICollection<Stage> Stages { get; set; }
    }
}
