//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.Detail_Semaine = new HashSet<Detail_Semaine>();
        }
    
        public int noSTAGE { get; set; }
        public int noStagiaire { get; set; }
        public int noSuperviseur { get; set; }
        public int noTuteur { get; set; }
        public int noENT { get; set; }
        public System.DateTime dateDebut { get; set; }
        public int nbSemaine { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
    
        public virtual ICollection<Detail_Semaine> Detail_Semaine { get; set; }
        public virtual Entreprise Entreprise { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
        public virtual Utilisateur Utilisateur2 { get; set; }
    }
}
