//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Utilisateur
    {
        public Type_Utilisateur()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }
    
        public int noTYPE { get; set; }
        public string libelleTYPE { get; set; }
    
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
