//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Stages = new HashSet<Stage>();
            this.Stages1 = new HashSet<Stage>();
            this.Stages2 = new HashSet<Stage>();
        }
    
        public int noUTIL { get; set; }
        public string nomUTIL { get; set; }
        public string prenomUTIL { get; set; }
        public string courrielUTIL { get; set; }
        public string telUTIL { get; set; }
        public int noTYPE { get; set; }
        public string mdp { get; set; }
        public Nullable<System.DateTime> dateSuppression { get; set; }
    
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Stage> Stages1 { get; set; }
        public virtual ICollection<Stage> Stages2 { get; set; }
        public virtual Type_Utilisateur Type_Utilisateur { get; set; }
    }
}
